var words = [
  { latin: "canis", english: ["dog"], stage: "1" },
  { latin: "coquus", english: ["cook"], stage: "1", part: "noun" },
  { latin: "est", english: ["is"], stage: "1", part: "verb" },
  { latin: "filius", english: ["son"], stage: "1", part: "noun" },
  { latin: "hortus", english: ["garden"], stage: "1", part: "noun" },
  { latin: "in", english: ["in"], stage: "1", part: "prep." },
  { latin: "laborat", english: ["works", "is working"], stage: "1" },
  { latin: "mater", english: ["mother"], stage: "1", part: "noun" },
  { latin: "pater", english: ["father"], stage: "1" },
  { latin: "sedet", english: ["sits", "is sitting"], stage: "1" },
  { latin: "servus", english: ["slave"], stage: "1", part: "noun" },
  { latin: "via", english: ["street", "road"], stage: "1" },
  { latin: "amicus", english: ["friend"], stage: "2" },
  {
    latin: "ancilla",
    english: ["slave-girl", "maid"],
    stage: "2",
    part: "noun",
  },
  { latin: "cena", english: ["dinner"], stage: "2", part: "noun" },
  { latin: "cibus", english: ["food"], stage: "2", part: "noun" },
  { latin: "dominus", english: ["master"], stage: "2", part: "noun" },
  { latin: "dormit", english: ["sleeps"], stage: "2", part: "verb" },
  { latin: "intrat", english: ["enters"], stage: "2", part: "verb" },
  { latin: "laetus", english: ["happy"], stage: "2" },
  { latin: "laudat", english: ["praises"], stage: "2", part: "verb" },
  { latin: "mercator", english: ["merchant"], stage: "2" },
  { latin: "quoque", english: ["also"], stage: "2" },
  { latin: "salutat", english: ["greets"], stage: "2" },
  { latin: "ad", english: ["to"], stage: "3" },
  { latin: "bibit", english: ["drinks"], stage: "3" },
  { latin: "circumspectat", english: ["looks around"], stage: "3" },
  { latin: "clamat", english: ["shouts"], stage: "3" },
  {
    latin: "ecce",
    english: ["look"],
    stage: "3",
    part: "interjection",
  },
  { latin: "et", english: ["and"], stage: "3", part: "conjunction" },
  { latin: "exit", english: ["goes out"], stage: "3" },
  {
    latin: "exspectat",
    english: ["waits for"],
    stage: "3",
    part: "verb",
  },
  { latin: "ianua", english: ["door"], stage: "3" },
  { latin: "iratus", english: ["angry"], stage: "3", part: "adj." },
  { latin: "leo", english: ["lion"], stage: "3", part: "noun" },
  { latin: "magnus", english: ["big"], stage: "3" },
  { latin: "navis", english: ["ship"], stage: "3" },
  { latin: "non", english: ["not"], stage: "3", part: "adv." },
  { latin: "portat", english: ["carries"], stage: "3", part: "verb" },
  {
    latin: "respondet",
    english: ["replies"],
    stage: "3",
    part: "verb",
  },
  { latin: "ridet", english: ["laughs", "smiles"], stage: "3" },
  {
    latin: "salve",
    english: ["hello", "hi"],
    stage: "3",
    part: "inter.",
  },
  {
    latin: "surgit",
    english: ["gets up", "stands up"],
    stage: "3",
    part: "verb",
  },
  { latin: "taberna", english: ["shop", "inn"], stage: "3" },
  { latin: "videt", english: ["sees"], stage: "3", part: "verb" },
  { latin: "vinum", english: ["wine"], stage: "3", part: "noun" },
  { latin: "agit", english: ["does"], stage: "4" },
  { latin: "anulus", english: ["ring"], stage: "4", part: "noun" },
  { latin: "coquit", english: ["cooks"], stage: "4" },
  { latin: "cur?", english: ["why?"], stage: "4" },
  { latin: "e", english: ["from", "out of"], stage: "4" },
  { latin: "ego", english: ["i"], stage: "4" },
  {
    latin: "eheu",
    english: ["oh dear", "oh no"],
    stage: "4",
    part: "interjection",
  },
  { latin: "habet", english: ["has"], stage: "4" },
  { latin: "inquit", english: ["says"], stage: "4", part: "verb" },
  { latin: "iudex", english: ["judge"], stage: "4", part: "noun" },
  { latin: "mendax", english: ["liar"], stage: "4" },
  { latin: "pecunia", english: ["money"], stage: "4" },
  { latin: "perterritus", english: ["terrified"], stage: "4" },
  { latin: "poeta", english: ["poet"], stage: "4" },
  {
    latin: "quaerit",
    english: ["looks for", "searches for"],
    stage: "4",
  },
  { latin: "quis?", english: ["who?"], stage: "4" },
  {
    latin: "reddit",
    english: ["gives back"],
    stage: "4",
    part: "verb",
  },
  { latin: "satis", english: ["enough"], stage: "4" },
  { latin: "sed", english: ["but"], stage: "4" },
  {
    latin: "signum",
    english: ["sign", "seal"],
    stage: "4",
    part: "noun",
  },
  { latin: "tu", english: ["you"], stage: "4" },
  { latin: "vocat", english: ["calls"], stage: "4", part: "verb" },
  { latin: "adest", english: ["is here"], stage: "5" },
  { latin: "adsunt", english: ["are here"], stage: "5" },
  { latin: "agricola", english: ["farmer"], stage: "5", part: "noun" },
  { latin: "ambulat", english: ["walks"], stage: "5" },
  { latin: "audit", english: ["hears"], stage: "5", part: "verb" },
  {
    latin: "clamor",
    english: ["shout", "uproar"],
    stage: "5",
    part: "noun",
  },
  { latin: "contendit", english: ["hurries"], stage: "5" },
  { latin: "currit", english: ["runs"], stage: "5", part: "verb" },
  { latin: "fabula", english: ["play", "story"], stage: "5" },
  { latin: "femina", english: ["woman"], stage: "5" },
  { latin: "hodie", english: ["today"], stage: "5" },
  {
    latin: "iuvenis",
    english: ["young man"],
    stage: "5",
    part: "noun",
  },
  { latin: "meus", english: ["my", "mine"], stage: "5" },
  { latin: "multi", english: ["many"], stage: "5" },
  { latin: "multus", english: ["much"], stage: "5" },
  { latin: "optimus", english: ["very good", "excellent"], stage: "5" },
  { latin: "petit", english: ["makes for", "attacks"], stage: "5" },
  { latin: "plaudit", english: ["applauds"], stage: "5" },
  { latin: "puella", english: ["girl"], stage: "5" },
  { latin: "senex", english: ["old man"], stage: "5", part: "noun" },
  {
    latin: "spectat",
    english: ["looks at", "watches"],
    stage: "5",
    part: "verb",
  },
  { latin: "stat", english: ["stands"], stage: "5" },
  { latin: "turba", english: ["crowd"], stage: "5", part: "noun" },
  { latin: "ubi?", english: ["where?"], stage: "5" },
  { latin: "urbs", english: ["city"], stage: "5", part: "noun" },
  { latin: "venit", english: ["comes"], stage: "5" },
  {
    latin: "aberat",
    english: ["was out", "was absent"],
    stage: "6",
    part: "verb",
  },
  {
    latin: "abest",
    english: ["is out", "is absent"],
    stage: "6",
    part: "verb",
  },
  {
    latin: "cubiculum",
    english: ["bedroom"],
    stage: "6",
    part: "noun",
  },
  { latin: "emit", english: ["buys"], stage: "6", part: "verb" },
  { latin: "ferociter", english: ["fiercely"], stage: "6" },
  { latin: "festinat", english: ["hurries"], stage: "6" },
  { latin: "fortis", english: ["brave"], stage: "6" },
  { latin: "fur", english: ["thief"], stage: "6", part: "noun" },
  {
    latin: "intente",
    english: ["intently", "carefully"],
    stage: "6",
    part: "adv",
  },
  { latin: "libertus", english: ["freedman", "ex-slave"], stage: "6" },
  { latin: "olim", english: ["once", "some time ago"], stage: "6" },
  { latin: "parvus", english: ["small"], stage: "6" },
  { latin: "per", english: ["through"], stage: "6" },
  { latin: "postquam", english: ["after"], stage: "6" },
  { latin: "pulsat", english: ["hits", "thumps"], stage: "6" },
  { latin: "quod", english: ["because"], stage: "6" },
  { latin: "res", english: ["thing"], stage: "6", part: "noun" },
  { latin: "scribit", english: ["writes"], stage: "6" },
  { latin: "subito", english: ["suddenly"], stage: "6" },
  {
    latin: "superat",
    english: ["overcomes", "overpowers"],
    stage: "6",
  },
  { latin: "tum", english: ["then"], stage: "6", part: "adv." },
  { latin: "tuus", english: ["your", "yours"], stage: "6" },
  { latin: "vendit", english: ["sells"], stage: "6", part: "verb" },
  { latin: "vituperat", english: ["blames", "curses"], stage: "6" },
  { latin: "cenat", english: ["dines"], stage: "7" },
  { latin: "conspicit", english: ["catches sight of"], stage: "7" },
  { latin: "cum", english: ["with"], stage: "7" },
  {
    latin: "facit",
    english: ["makes", "does"],
    stage: "7",
    part: "verb",
  },
  { latin: "heri", english: ["yesterday"], stage: "7", part: "adv." },
  { latin: "ingens", english: ["huge"], stage: "7", part: "adj." },
  { latin: "intellegit", english: ["understands"], stage: "7" },
  { latin: "lacrimat", english: ["weeps", "cries"], stage: "7" },
  { latin: "mortuus", english: ["dead"], stage: "7" },
  { latin: "narrat", english: ["tells", "relates"], stage: "7" },
  { latin: "necat", english: ["kills"], stage: "7" },
  { latin: "nihil", english: ["nothing"], stage: "7" },
  { latin: "omnis", english: ["all"], stage: "7", part: "adj." },
  { latin: "parat", english: ["prepares"], stage: "7" },
  { latin: "prope", english: ["near"], stage: "7" },
  { latin: "rogat", english: ["asks"], stage: "7" },
  { latin: "tacite", english: ["quietly"], stage: "7", part: "adv" },
  { latin: "tamen", english: ["however"], stage: "7" },
  { latin: "terret", english: ["frightens"], stage: "7" },
  { latin: "valde", english: ["very much"], stage: "7", part: "adv" },
  {
    latin: "agitat",
    english: ["chases", "hunts"],
    stage: "8",
    part: "verb",
  },
  { latin: "consumit", english: ["eats"], stage: "8" },
  { latin: "ducit", english: ["leads", "takes"], stage: "8" },
  { latin: "eum", english: ["him"], stage: "8" },
  { latin: "facile", english: ["easily"], stage: "8", part: "adv." },
  { latin: "ferox", english: ["fierce"], stage: "8" },
  { latin: "gladius", english: ["sword"], stage: "8" },
  { latin: "hic", english: ["this"], stage: "8" },
  { latin: "ignavus", english: ["cowardly"], stage: "8" },
  {
    latin: "nuntius",
    english: ["messenger"],
    stage: "8",
    part: "noun",
  },
  { latin: "pes", english: ["foot"], stage: "8", part: "noun" },
  { latin: "porta", english: ["gate"], stage: "8", part: "noun" },
  { latin: "postulat", english: ["demands"], stage: "8" },
  { latin: "puer", english: ["boy"], stage: "8", part: "noun" },
  { latin: "pugnat", english: ["fights"], stage: "8" },
  { latin: "saepe", english: ["often"], stage: "8" },
  { latin: "sanguis", english: ["blood"], stage: "8", part: "noun" },
  {
    latin: "silva",
    english: ["wood", "forest"],
    stage: "8",
    part: "noun",
  },
  { latin: "spectaculum", english: ["show", "spectacle"], stage: "8" },
  { latin: "statim", english: ["at once"], stage: "8" },
  { latin: "totus", english: ["whole"], stage: "8", part: "adj." },
  { latin: "agnoscit", english: ["recognises"], stage: "9" },
  { latin: "celeriter", english: ["quickly"], stage: "9" },
  { latin: "cupit", english: ["wants"], stage: "9", part: "verb" },
  { latin: "dat", english: ["gives"], stage: "9", part: "verb" },
  { latin: "dies", english: ["day"], stage: "9" },
  { latin: "emittit", english: ["throws", "sends out"], stage: "9" },
  { latin: "fert", english: ["brings", "carries"], stage: "9" },
  { latin: "homo", english: ["human being", "man"], stage: "9" },
  { latin: "hospes", english: ["guest"], stage: "9", part: "noun" },
  { latin: "ille", english: ["that"], stage: "9", part: "pro." },
  { latin: "inspicit", english: ["looks at", "examines"], stage: "9" },
  { latin: "iterum", english: ["again"], stage: "9", part: "adv." },
  {
    latin: "manet",
    english: ["remains", "stays"],
    stage: "9",
    part: "verb",
  },
  { latin: "medius", english: ["middle"], stage: "9" },
  { latin: "mox", english: ["soon"], stage: "9", part: "adv." },
  { latin: "offert", english: ["offers"], stage: "9" },
  { latin: "ostendit", english: ["shows"], stage: "9" },
  { latin: "post", english: ["after"], stage: "9" },
  { latin: "procedit", english: ["proceeds", "advances"], stage: "9" },
  { latin: "pulcher", english: ["beautiful"], stage: "9" },
  {
    latin: "revenit",
    english: ["comes back", "returns"],
    stage: "9",
    part: "verb",
  },
  {
    latin: "tradit",
    english: ["hands over"],
    stage: "9",
    part: "verb",
  },
  { latin: "abit", english: ["goes away"], stage: "10" },
  { latin: "accipit", english: ["accepts"], stage: "10" },
  {
    latin: "callidus",
    english: ["clever", "cunning"],
    stage: "10",
    part: "adj.",
  },
  { latin: "contentus", english: ["satisfied"], stage: "10" },
  { latin: "exclamat", english: ["exclaims"], stage: "10" },
  { latin: "frater", english: ["brother"], stage: "10" },
  { latin: "habitat", english: ["lives"], stage: "10" },
  { latin: "imperium", english: ["empire"], stage: "10", part: "noun" },
  { latin: "invenit", english: ["finds"], stage: "10" },
  { latin: "liber", english: ["book"], stage: "10", part: "noun" },
  { latin: "nos", english: ["we"], stage: "10" },
  { latin: "nuntiat", english: ["announces"], stage: "10" },
  { latin: "pax", english: ["peace"], stage: "10" },
  { latin: "portus", english: ["harbour"], stage: "10", part: "noun" },
  { latin: "quam", english: ["than"], stage: "10" },
  { latin: "semper", english: ["always"], stage: "10" },
  { latin: "servat", english: ["saves", "looks after"], stage: "10" },
  { latin: "solus", english: ["alone"], stage: "10" },
  { latin: "suus", english: ["his", "her"], stage: "10", part: "adj." },
  { latin: "tacet", english: ["is silent", "is quiet"], stage: "10" },
  { latin: "uxor", english: ["wife"], stage: "10", part: "noun" },
  {
    latin: "vehementer",
    english: ["violently", "loudly"],
    stage: "10",
  },
  {
    latin: "vos",
    english: ["you (plural)", "yall", "you all", "y'all"],
    stage: "10",
    part: "pro.",
  },
  { latin: "capit", english: ["takes"], stage: "11", part: "verb" },
  { latin: "civis", english: ["citizen"], stage: "11", part: "noun" },
  { latin: "convenit", english: ["gathers", "meets"], stage: "11" },
  { latin: "credit", english: ["trusts", "believes"], stage: "11" },
  { latin: "de", english: ["about"], stage: "11", part: "prep." },
  { latin: "favet", english: ["supports"], stage: "11", part: "verb" },
  { latin: "invitat", english: ["invites"], stage: "11", part: "verb" },
  { latin: "it", english: ["goes"], stage: "11" },
  { latin: "legit", english: ["reads"], stage: "11", part: "verb" },
  {
    latin: "liberalis",
    english: ["generous"],
    stage: "11",
    part: "adj.",
  },
  { latin: "minime", english: ["no"], stage: "11" },
  { latin: "murus", english: ["wall"], stage: "11", part: "noun" },
  { latin: "noster", english: ["our"], stage: "11", part: "pro." },
  { latin: "nunc", english: ["now"], stage: "11" },
  {
    latin: "placet",
    english: ["it pleases"],
    stage: "11",
    part: "verb",
  },
  { latin: "primus", english: ["first"], stage: "11" },
  { latin: "promittit", english: ["promises"], stage: "11" },
  { latin: "pugna", english: ["fight"], stage: "11", part: "noun" },
  { latin: "senator", english: ["senator"], stage: "11" },
  { latin: "sollicitus", english: ["worried", "anxious"], stage: "11" },
  { latin: "stultus", english: ["stupid"], stage: "11" },
  {
    latin: "vale",
    english: ["goodbye", "bye"],
    stage: "11",
    part: "inter.",
  },
  { latin: "verbero", english: ["strikes", "beats"], stage: "11" },
  { latin: "vir", english: ["man"], stage: "11", part: "noun" },
  { latin: "amittit", english: ["loses"], stage: "12" },
  { latin: "complet", english: ["fills"], stage: "12", part: "verb" },
  { latin: "custodit", english: ["guards"], stage: "12", part: "verb" },
  { latin: "duo", english: ["two"], stage: "12", part: "adj." },
  { latin: "epistula", english: ["letter"], stage: "12", part: "noun" },
  { latin: "flamma", english: ["flame"], stage: "12" },
  {
    latin: "fortiter",
    english: ["bravely"],
    stage: "12",
    part: "adv.",
  },
  { latin: "frustra", english: ["in vain"], stage: "12" },
  {
    latin: "fugit",
    english: ["runs away", "flees"],
    stage: "12",
    part: "verb",
  },
  { latin: "fundus", english: ["farm"], stage: "12" },
  { latin: "iacet", english: ["lies"], stage: "12" },
  { latin: "iam", english: ["now"], stage: "12" },
  { latin: "igitur", english: ["therefore"], stage: "12" },
  {
    latin: "mirabilis",
    english: ["strange", "extraordinary"],
    stage: "12",
  },
  { latin: "mittit", english: ["sends"], stage: "12", part: "verb" },
  { latin: "mons", english: ["mountain"], stage: "12", part: "noun" },
  { latin: "optime", english: ["very well"], stage: "12", part: "adv" },
  { latin: "paene", english: ["nearly", "almost"], stage: "12" },
  { latin: "sentit", english: ["feels"], stage: "12", part: "verb" },
  { latin: "tandem", english: ["at last"], stage: "12" },
  { latin: "templum", english: ["temple"], stage: "12", part: "noun" },
  {
    latin: "terra",
    english: ["ground", "land"],
    stage: "12",
    part: "noun",
  },
  { latin: "timet", english: ["is afraid", "fears"], stage: "12" },
  { latin: "tres", english: ["three"], stage: "12" },
  { latin: "unus", english: ["one"], stage: "12", part: "adj." },
  { latin: "advenio", english: ["arrive"], stage: "13" },
  { latin: "aedificium", english: ["building"], stage: "13" },
  {
    latin: "aeger",
    english: ["sick", "ill"],
    stage: "13",
    part: "adj.",
  },
  {
    latin: "alter",
    english: ["the other", "the second "],
    stage: "13",
  },
  { latin: "canto", english: ["sing"], stage: "13" },
  { latin: "ceteri", english: ["the others", "the rest"], stage: "13" },
  { latin: "custos", english: ["guard"], stage: "13", part: "noun" },
  { latin: "dico", english: ["say"], stage: "13" },
  {
    latin: "excito",
    english: ["arouse", "wake up"],
    stage: "13",
    part: "verb",
  },
  { latin: "fessus", english: ["tired"], stage: "13", part: "adj." },
  { latin: "interficio", english: ["kill"], stage: "13" },
  { latin: "ita vero", english: ["yes"], stage: "13" },
  {
    latin: "nolo",
    english: ["i do not want", "i dont want", "i don't want"],
    stage: "13",
  },
  { latin: "novus", english: ["new"], stage: "13" },
  {
    latin: "nullus",
    english: ["not any", "no"],
    stage: "13",
    part: "adj.",
  },
  { latin: "possum", english: ["i can", "i am able"], stage: "13" },
  { latin: "ruo", english: ["rush"], stage: "13" },
  { latin: "se", english: ["himself"], stage: "13" },
  { latin: "traho", english: ["drag"], stage: "13", part: "verb" },
  { latin: "vita", english: ["life"], stage: "13" },
  { latin: "volo", english: ["i want"], stage: "13", part: "verb" },
  { latin: "vulnero", english: ["wound"], stage: "13", part: "verb" },
  { latin: "-que", english: ["and"], stage: "14" },
  { latin: "aliquid", english: ["something"], stage: "14" },
  {
    latin: "apud",
    english: ["among", "at the house of"],
    stage: "14",
    part: "prep.",
  },
  {
    latin: "attonitus",
    english: ["astonished"],
    stage: "14",
    part: "adj.",
  },
  { latin: "aula", english: ["palace"], stage: "14", part: "noun" },
  { latin: "cotidie", english: ["every day"], stage: "14" },
  { latin: "decorus", english: ["right", "proper"], stage: "14" },
  { latin: "deleo", english: ["destroy"], stage: "14" },
  { latin: "deus", english: ["god"], stage: "14", part: "noun" },
  { latin: "difficilis", english: ["difficult"], stage: "14" },
  {
    latin: "diligenter",
    english: ["careful"],
    stage: "14",
    part: "adv",
  },
  { latin: "domina", english: ["mistress"], stage: "14" },
  {
    latin: "donum",
    english: ["present", "gift"],
    stage: "14",
    part: "noun",
  },
  { latin: "fidelis", english: ["faithful", "loyal"], stage: "14" },
  { latin: "ipse", english: ["himself", "herself"], stage: "14" },
  { latin: "iste", english: ["that"], stage: "14", part: "pro." },
  { latin: "maritus", english: ["husband"], stage: "14" },
  {
    latin: "necesse",
    english: ["necessary"],
    stage: "14",
    part: "adj.",
  },
  { latin: "num?", english: ["surely not?"], stage: "14" },
  { latin: "quam", english: ["how"], stage: "14" },
  { latin: "quamquam", english: ["although"], stage: "14" },
  { latin: "rex", english: ["king"], stage: "14", part: "noun" },
  { latin: "ubi", english: ["when"], stage: "14", part: "adv." },
  {
    latin: "agmen",
    english: ["column (of men)", "procession"],
    stage: "15",
  },
  {
    latin: "alius",
    english: ["other", "another"],
    stage: "15",
    part: "adj.",
  },
  { latin: "aqua", english: ["water"], stage: "15", part: "noun" },
  {
    latin: "claudo",
    english: ["shut", "block"],
    stage: "15",
    part: "verb",
  },
  { latin: "commodus", english: ["convenient"], stage: "15" },
  {
    latin: "debeo",
    english: ["owe", "ought"],
    stage: "15",
    part: "verb",
  },
  { latin: "equus", english: ["horse"], stage: "15" },
  { latin: "etiam", english: ["even"], stage: "15", part: "adv." },
  {
    latin: "impedio",
    english: ["delay", "hinder"],
    stage: "15",
    part: "verb",
  },
  { latin: "lectus", english: ["couch"], stage: "15" },
  { latin: "lente", english: ["slowly"], stage: "15", part: "adv." },
  { latin: "litus", english: ["sea-shore"], stage: "15", part: "noun" },
  { latin: "mare", english: ["sea"], stage: "15" },
  { latin: "miser", english: ["miserable", "wretched"], stage: "15" },
  { latin: "nauta", english: ["sailor"], stage: "15" },
  {
    latin: "princeps",
    english: ["chief", "chieftain"],
    stage: "15",
    part: "noun",
  },
  { latin: "qui", english: ["who"], stage: "15", part: "pro." },
  {
    latin: "redeo",
    english: ["return", "go back"],
    stage: "15",
    part: "verb",
  },
  { latin: "sacerdos", english: ["priest"], stage: "15", part: "noun" },
  { latin: "teneo", english: ["hold"], stage: "15", part: "verb" },
  { latin: "unda", english: ["wave"], stage: "15" },
  { latin: "aedifico", english: ["build"], stage: "16" },
  { latin: "auxilium", english: ["help"], stage: "16", part: "noun" },
  { latin: "bonus", english: ["good"], stage: "16" },
  { latin: "consentio", english: ["agree"], stage: "16" },
  { latin: "consilium", english: ["plan", "idea"], stage: "16" },
  { latin: "deinde", english: ["then"], stage: "16", part: "adv." },
  { latin: "delecto", english: ["delight"], stage: "16" },
  { latin: "effugio", english: ["escape"], stage: "16" },
  { latin: "flos", english: ["flower"], stage: "16", part: "noun" },
  { latin: "imperator", english: ["emperor"], stage: "16" },
  { latin: "inter", english: ["among"], stage: "16" },
  { latin: "ita", english: ["in this way"], stage: "16" },
  { latin: "melior", english: ["better"], stage: "16", part: "adj." },
  { latin: "navigo", english: ["sail"], stage: "16", part: "verb" },
  {
    latin: "nonne?",
    english: ["surely?"],
    stage: "16",
    part: "particle",
  },
  { latin: "pereo", english: ["die", "perish"], stage: "16" },
  { latin: "pono", english: ["place", "put"], stage: "16" },
  { latin: "postridie", english: ["on the next day"], stage: "16" },
  { latin: "punio", english: ["punish"], stage: "16" },
  { latin: "simulac", english: ["as soon as"], stage: "16" },
  {
    latin: "summus",
    english: ["highest", "greatest"],
    stage: "16",
    part: "adj.",
  },
  { latin: "tollo", english: ["raise", "lift up"], stage: "16" },
  { latin: "verto", english: ["turn"], stage: "16", part: "verb" },
  { latin: "a, ab", english: ["from"], stage: "17", part: "prep." },
  {
    latin: "animus",
    english: ["spirit", "soul"],
    stage: "17",
    part: "noun",
  },
  {
    latin: "appropinquo",
    english: ["approach", "come near to"],
    stage: "17",
    part: "verb",
  },
  { latin: "ara", english: ["altar"], stage: "17", part: "noun" },
  { latin: "bene", english: ["well"], stage: "17" },
  { latin: "benignus", english: ["kind"], stage: "17" },
  { latin: "diu", english: ["for a long time"], stage: "17" },
  { latin: "faber", english: ["craftsman"], stage: "17" },
  { latin: "facilis", english: ["easy"], stage: "17" },
  {
    latin: "graviter",
    english: ["seriously"],
    stage: "17",
    part: "adv.",
  },
  { latin: "huc", english: ["here", "to this place"], stage: "17" },
  { latin: "insula", english: ["island"], stage: "17" },
  {
    latin: "invitus",
    english: ["unwilling", "reluctant"],
    stage: "17",
  },
  { latin: "itaque", english: ["and so"], stage: "17" },
  { latin: "maximus", english: ["very big"], stage: "17" },
  { latin: "negotium", english: ["business"], stage: "17" },
  { latin: "numquam", english: ["never"], stage: "17" },
  { latin: "pauci", english: ["few", "a few"], stage: "17" },
  {
    latin: "pervenio",
    english: ["reach", "arrive at"],
    stage: "17",
    part: "verb",
  },
  { latin: "quondam", english: ["one day", "once"], stage: "17" },
  {
    latin: "recipio",
    english: ["recover", "take back"],
    stage: "17",
    part: "verb",
  },
  { latin: "resisto", english: ["resist"], stage: "17" },
  { latin: "audeo", english: ["dare"], stage: "18", part: "verb" },
  { latin: "caput", english: ["head"], stage: "18", part: "noun" },
  { latin: "coepi", english: ["i began"], stage: "18", part: "verb" },
  {
    latin: "cognosco",
    english: ["get to know", "find out"],
    stage: "18",
    part: "verb",
  },
  { latin: "dea", english: ["goddess"], stage: "18" },
  { latin: "demonstro", english: ["point out", "show"], stage: "18" },
  { latin: "discedo", english: ["depart", "leave"], stage: "18" },
  { latin: "fortasse", english: ["perhaps"], stage: "18" },
  { latin: "ibi", english: ["there"], stage: "18" },
  {
    latin: "libens",
    english: ["willing", "glad"],
    stage: "18",
    part: "adj.",
  },
  { latin: "manus", english: ["hand"], stage: "18", part: "noun" },
  { latin: "miles", english: ["soldier"], stage: "18", part: "noun" },
  { latin: "nam", english: ["for"], stage: "18", part: "conj." },
  { latin: "nemo", english: ["no one"], stage: "18", part: "pro." },
  {
    latin: "obsto",
    english: ["obstruct", "block the way"],
    stage: "18",
  },
  { latin: "pars", english: ["part"], stage: "18", part: "noun" },
  { latin: "peto", english: ["beg for", "ask for"], stage: "18" },
  {
    latin: "postea",
    english: ["afterwards"],
    stage: "18",
    part: "adv",
  },
  { latin: "pro", english: ["in front of"], stage: "18" },
  {
    latin: "quo?",
    english: ["where?", "where to?"],
    stage: "18",
    part: "adv",
  },
  { latin: "recuso", english: ["refuse"], stage: "18" },
  {
    latin: "soleo",
    english: ["be accustomed"],
    stage: "18",
    part: "verb",
  },
  {
    latin: "amo",
    english: ["love", "like"],
    stage: "19",
    part: "verb",
  },
  { latin: "carus", english: ["dear"], stage: "19" },
  { latin: "cogito", english: ["think", "consider"], stage: "19" },
  { latin: "comparo", english: ["obtain"], stage: "19", part: "verb" },
  { latin: "conficio", english: ["finish"], stage: "19", part: "verb" },
  { latin: "curo", english: ["look after"], stage: "19" },
  { latin: "filia", english: ["daughter"], stage: "19" },
  { latin: "fluo", english: ["flow"], stage: "19" },
  { latin: "forte", english: ["by chance"], stage: "19" },
  {
    latin: "gratias ago",
    english: ["i thank", "give thanks"],
    stage: "19",
  },
  { latin: "hasta", english: ["spear"], stage: "19" },
  { latin: "illuc", english: ["there", "to that place"], stage: "19" },
  { latin: "iter", english: ["journey"], stage: "19", part: "noun" },
  { latin: "locus", english: ["place"], stage: "19" },
  {
    latin: "mane",
    english: ["in the morning"],
    stage: "19",
    part: "adv",
  },
  { latin: "novi", english: ["know"], stage: "19" },
  {
    latin: "periculum",
    english: ["danger"],
    stage: "19",
    part: "noun",
  },
  {
    latin: "plurimi",
    english: ["very many"],
    stage: "19",
    part: "adj.",
  },
  {
    latin: "posco",
    english: ["demand", "ask for"],
    stage: "19",
    part: "verb",
  },
  { latin: "tot", english: ["so many"], stage: "19" },
  { latin: "vexo", english: ["annoy"], stage: "19" },
  { latin: "vivo", english: ["live"], stage: "19" },
  { latin: "vix", english: ["hardly", "scarcely"], stage: "19" },
  { latin: "vox", english: ["voice"], stage: "19", part: "noun" },
  {
    latin: "adeo",
    english: ["go to", "approach"],
    stage: "20",
    part: "verb",
  },
  { latin: "arcesso", english: ["summon", "send for"], stage: "20" },
  { latin: "ars", english: ["art"], stage: "20", part: "noun" },
  { latin: "crudelis", english: ["cruel"], stage: "20" },
  { latin: "decem", english: ["ten"], stage: "20", part: "numeral" },
  { latin: "denique", english: ["at last", "finally"], stage: "20" },
  { latin: "despero", english: ["despair"], stage: "20" },
  {
    latin: "doctus",
    english: ["learned", "clever"],
    stage: "20",
    part: "adj.",
  },
  { latin: "domus", english: ["home"], stage: "20", part: "noun" },
  { latin: "duo", english: ["two"], stage: "20" },
  {
    latin: "infero",
    english: ["bring in", "bring on"],
    stage: "20",
    part: "verb",
  },
  {
    latin: "libero",
    english: ["free", "set free"],
    stage: "20",
    part: "verb",
  },
  { latin: "luna", english: ["moon"], stage: "20" },
  { latin: "mors", english: ["death"], stage: "20", part: "noun" },
  { latin: "novem", english: ["nine"], stage: "20" },
  { latin: "octo", english: ["eight"], stage: "20", part: "numeral" },
  { latin: "oculus", english: ["eye"], stage: "20" },
  { latin: "persuadeo", english: ["persuade"], stage: "20" },
  { latin: "pessimus", english: ["very bad", "worst"], stage: "20" },
  {
    latin: "quadraginta",
    english: ["forty"],
    stage: "20",
    part: "adj.",
  },
  { latin: "quattuor", english: ["four"], stage: "20", part: "adj." },
  {
    latin: "quinquaginta",
    english: ["fifty"],
    stage: "20",
    part: "numeral",
  },
  { latin: "quinque", english: ["five"], stage: "20", part: "numeral" },
  { latin: "relinquo", english: ["leave"], stage: "20", part: "verb" },
  { latin: "septem", english: ["seven"], stage: "20", part: "adj." },
  { latin: "sex", english: ["six"], stage: "20" },
  { latin: "sicut", english: ["like"], stage: "20" },
  { latin: "tam", english: ["so"], stage: "20", part: "adv." },
  { latin: "tempto", english: ["try"], stage: "20", part: "verb" },
  { latin: "tres", english: ["three"], stage: "20", part: "ad." },
  { latin: "triginta", english: ["thirty"], stage: "20" },
  { latin: "unus", english: ["one"], stage: "20", part: "adj." },
  { latin: "viginti", english: ["twenty"], stage: "20" },
  { latin: "vulnus", english: ["wound"], stage: "20", part: "noun" },
];
